# See: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html

language: python
python:
  # Might not have any effect as Python version defined by Conda environment
  - "3.6"
install:
  # - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create the Conda environment
  - conda env create -f environment.yml
  - source activate ceasiompy
  - python setup.py install

script:
  - tox
after_success:
  - codecov
