coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unittests
          - integrationtests
        paths: 
          - "ceasiompy"
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: true
    patch: off