coverage:
  ignore:
    - "src/ceasiompy/SUMOAutoMesh/*"
    - "src/ceasiompy/SU2MeshDef/*"
    - "src/ceasiompy/utils/*"
    - "src/ceasiompy/Range/*"
    - "src/ceasiompy/ModuleTemplate/*"
    - "src/ceasiompy/BalanceConventional/*"
    - "src/ceasiompy/BalanceUnconventional/*"
    - "src/ceasiompy/WeightConventional/*"
    - "src/ceasiompy/WeightUnconventional/*"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto 
        flags: 
          - unittests
          - integrationtests
        paths: 
          - "ceasiompy"
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: true
        only_pulls: true
    patch: off