#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pathlib import Path

from ceasiompy.utils.moduleinterfaces import CPACSInOut
from ceasiompy.utils.commonxpath import CEASIOMPY_XPATH, MESH_XPATH

# ===== Results directory path =====

RESULTS_DIR = Path("Results", "GMSH")


# ===== CPACS inputs and outputs =====

cpacs_inout = CPACSInOut()

# ----- Input -----

cpacs_inout.add_input(
    var_name="open_gmsh",
    var_type=bool,
    default_value=False,
    unit="1",
    descr="Open GMSH GUI when the mesh is created",
    xpath=CEASIOMPY_XPATH + "/gmsh/open_gui",
    gui=True,
    gui_name="Display mesh with GMSH",
    gui_group="General options",
)

cpacs_inout.add_input(
    var_name="symmetry",
    var_type=bool,
    default_value=False,
    unit="1",
    descr="Create a symmetry condition",
    xpath=CEASIOMPY_XPATH + "/gmsh/symmetry",
    gui=True,
    gui_name="Use Symmetry",
    gui_group="Domain",
)

cpacs_inout.add_input(
    var_name="farfield_factor",
    var_type=float,
    default_value=6,
    unit="[-]",
    descr="Farfiled size factor compaire to the aircraft largest dimension",
    xpath=CEASIOMPY_XPATH + "/gmsh/farfield_factor",
    gui=True,
    gui_name="Farfield size factor",
    gui_group="Domain",
)

cpacs_inout.add_input(
    var_name="farfield_mesh_size",
    var_type=float,
    default_value=25,
    unit="[m]",
    descr="Value assigned for the farfield surface mesh size",
    xpath=CEASIOMPY_XPATH + "/gmsh/mesh_size/farfield",
    gui=True,
    gui_name="Farfield mesh size",
    gui_group="Mesh size",
)

cpacs_inout.add_input(
    var_name="fuselage_mesh_size",
    var_type=float,
    default_value=0.4,
    unit="[m]",
    descr="Value assigned for the fuselage surface mesh size",
    xpath=CEASIOMPY_XPATH + "/gmsh/mesh_size/fuselage",
    gui=True,
    gui_name="Fuselage mesh size",
    gui_group="Mesh size",
)


cpacs_inout.add_input(
    var_name="wing_mesh_size",
    var_type=float,
    default_value=0.23,
    unit="[m]",
    descr="Value assigned for the wings surface mesh size",
    xpath=CEASIOMPY_XPATH + "/gmsh/mesh_size/wings",
    gui=True,
    gui_name="Wings mesh size",
    gui_group="Mesh size",
)

cpacs_inout.add_input(
    var_name="refine_factor",
    var_type=float,
    default_value=7.0,
    unit="1",
    descr="Refinement factor of wing leading/trailing edge mesh",
    xpath=CEASIOMPY_XPATH + "/gmsh/refine_factor",
    gui=True,
    gui_name="Le/Te refinement factor",
    gui_group="Advanced mesh parameters",
)

cpacs_inout.add_input(
    var_name="intake_percent",
    var_type=float,
    default_value=20,
    unit="1",
    descr="Position of the intake surface boundary condition in percentage of"
    " the engine length from the beginning of the engine",
    xpath=CEASIOMPY_XPATH + "/gmsh/intake_percent",
    gui=True,
    gui_name="Engine intake position [%]",
    gui_group="Engines",
)
cpacs_inout.add_input(
    var_name="Exhaust_percent",
    var_type=float,
    default_value=20,
    unit="1",
    descr="Position of the exhaust surface boundary condition in percentage of"
    " the engine length from the end of the engine",
    xpath=CEASIOMPY_XPATH + "/gmsh/intake_percent",
    gui=True,
    gui_name="Engine exhaust position [%]",
    gui_group="Engines",
)
# ----- Output -----

cpacs_inout.add_output(
    var_name="gmsh_file_path",
    default_value=None,
    unit="1",
    descr="Path to the mesh file generated by CPACS2GMSH",
    xpath=MESH_XPATH + "/gmsh",
)
