#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path

from ceasiompy.utils.moduleinterfaces import CPACSInOut
from ceasiompy.utils.xpath import CEASIOMPY_XPATH, FUSELAGES_XPATH

# ===== Results directory path =====

RESULTS_DIR = Path("Results", "GMSH")


# ===== CPACS inputs and outputs =====

cpacs_inout = CPACSInOut()

# ----- Input -----

cpacs_inout.add_input(
    var_name="include_engine",
    var_type=bool,
    default_value=False,
    unit="1",
    descr="Convert engine from CEASIOMpy",
    xpath=CEASIOMPY_XPATH + "/engine/includeEngine",
    gui=True,
    gui_name="Include engine",
    gui_group="Option",
)


# ----- Output -----

# cpacs_inout.add_output(
#     var_name="gmsh_file_path",
#     default_value=None,
#     unit="1",
#     descr="Path to the mesh file generated by CPACS2GMSH",
#     xpath=GMSHFILE_XPATH,
# )
