from pathlib import Path

from ceasiompy.utils.commonxpath import (
    SUMO_INCLUDE_ENGINE_XPATH,
    SUMO_INCLUDE_PYLON_XPATH,
    SUMOFILE_XPATH,
)
from ceasiompy.utils.moduleinterfaces import CPACSInOut

# ===== Module Status =====
# True if the module is active
# False if the module is disabled (not working of not ready)
module_status = True

# ===== Results directory path =====

RESULTS_DIR = Path("Results", "SUMO")


# ===== CPACS inputs and outputs =====

cpacs_inout = CPACSInOut()

# ----- Input -----

cpacs_inout.add_input(
    var_name="include_engine",
    var_type=bool,
    default_value=False,
    unit="1",
    descr="Convert engine from CEASIOMpy",
    xpath=SUMO_INCLUDE_ENGINE_XPATH,
    gui=True,
    gui_name="Include engine",
    gui_group="Option",
)

cpacs_inout.add_input(
    var_name="include_pylon",
    var_type=bool,
    default_value=False,
    unit="1",
    descr="Convert engine from CEASIOMpy",
    xpath=SUMO_INCLUDE_PYLON_XPATH,
    gui=True,
    gui_name="Include pylon",
    gui_group="Option",
)


# ----- Output -----

cpacs_inout.add_output(
    var_name="sumo_file_path",
    default_value=None,
    unit="1",
    descr="Path to the SUMO file generated by CPACS2SUMO",
    xpath=SUMOFILE_XPATH,
)
