#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from ceasiompy.utils.moduleinterfaces import CPACSInOut, CEASIOM_XPATH


# ===== RCE integration =====

RCE = {
    "name": "CPACS2SUMO",
    "description": "Convert CPACS .xml file into SUMO .smx file",
    "exec": "pwd\npython cpacs2sumo.py",
    "author": "Aidan Jungo",
    "email": "aidan.jungo@cfse.ch",
}

# ===== CPACS inputs and outputs =====

cpacs_inout = CPACSInOut()

# ----- Input -----

cpacs_inout.add_input(
    var_name='include_engine',
    var_type=bool,
    default_value=False,
    unit='1',
    descr='Convert engine from CEASIOMpy',
    xpath=CEASIOM_XPATH + '/engine/includeEngine',
    gui=True,
    gui_name='Include engine',
    gui_group='Option',
)

cpacs_inout.add_input(
    var_name='include_pylon',
    var_type=bool,
    default_value=False,
    unit='1',
    descr='Convert engine from CEASIOMpy',
    xpath=CEASIOM_XPATH + '/engine/includePylon',
    gui=True,
    gui_name='Include pylon',
    gui_group='Option',
)


# ----- Output -----

cpacs_inout.add_output(
    var_name='sumo_file_path',
    default_value=None,
    unit='1',
    descr='Path to the SUMO file generated by CPACS2SUMO',
    xpath='/cpacs/toolspecific/CEASIOMpy/filesPath/sumoFilePath',
)
