"""
CEASIOMpy: Conceptual Aircraft Design Software

Developed by CFS ENGINEERING, 1015 Lausanne, Switzerland

GUI Interface of CPACS2SUMO.


| Author: Leon Deligny
| Creation: 18-Mar-2025

"""

# ==============================================================================
#   IMPORTS
# ==============================================================================

from ceasiompy.utils.moduleinterfaces import CPACSInOut

from ceasiompy import log
from ceasiompy.CPACSUpdater import include_gui

from ceasiompy.CPACS2SUMO import (
    CPACS2SUMOFILE_XPATH,
    CPACS2SUMO_INCLUDE_PYLON_XPATH,
    CPACS2SUMO_INCLUDE_ENGINE_XPATH,
    CPACS2SUMO_SUMO_GUI_XPATH,
)

# ==============================================================================
#   VARIABLE
# ==============================================================================

cpacs_inout = CPACSInOut()

# ==============================================================================
#   GUI INPUTS
# ==============================================================================

cpacs_inout.add_input(
    var_name="open_sumo_gui",
    var_type=bool,
    default_value=False,
    unit=None,
    descr="True -> Opens SUMO at the end of CPACS2SUMO module",
    xpath=CPACS2SUMO_SUMO_GUI_XPATH,
    gui=include_gui,
    gui_name="Open SUMO's GUI",
    gui_group="SUMO GUI Setting",
)

cpacs_inout.add_input(
    var_name="include_engine",
    var_type=bool,
    default_value=False,
    unit=None,
    descr="Convert engine from CEASIOMpy",
    xpath=CPACS2SUMO_INCLUDE_ENGINE_XPATH,
    gui=include_gui,
    gui_name="Include engine",
    gui_group="Mesh Settings",
)

cpacs_inout.add_input(
    var_name="include_pylon",
    var_type=bool,
    default_value=False,
    unit="1",
    descr="Convert engine from CEASIOMpy",
    xpath=CPACS2SUMO_INCLUDE_PYLON_XPATH,
    gui=include_gui,
    gui_name="Include pylon",
    gui_group="Mesh Settings",
)

# ==============================================================================
#   GUI OUTPUTS
# ==============================================================================

cpacs_inout.add_output(
    var_name="sumo_file_path",
    default_value=None,
    unit="1",
    descr="Path to the SUMO file generated by CPACS2SUMO",
    xpath=CPACS2SUMOFILE_XPATH,
)

# =================================================================================================
#    MAIN
# =================================================================================================

if __name__ == "__main__":
    log.info("Nothing to be executed.")
