"""
CEASIOMpy: Conceptual Aircraft Design Software

Developed by CFS ENGINEERING, 1015 Lausanne, Switzerland

Test functions for 'ceasiompy/CPACS2GMSH/exportbrep.py'
"""

# Imports

import shutil
import pytest

from ceasiompy.CPACS2GMSH.func.exportbrep import export_brep

from pathlib import Path
from cpacspy.cpacspy import CPACS

from unittest.mock import patch
from ceasiompy.utils.commonpaths import CPACS_FILES_PATH
from ceasiompy.CPACS2GMSH import MODULE_NAME as CPACS2GMSH

# Constants
MODULE_DIR = Path(__file__).parent
CPACS_IN_PATH = Path(CPACS_FILES_PATH, "simpletest_cpacs.xml")
CPACS_IN_SIMPLE_ENGINE_PATH = Path(CPACS_FILES_PATH, "simple_engine.xml")
TEST_OUT_PATH = Path(MODULE_DIR, "ToolOutput")


# Functions

def test_export_brep():
    """Test function for 'export_brep'"""

    if TEST_OUT_PATH.exists():
        shutil.rmtree(TEST_OUT_PATH)
    TEST_OUT_PATH.mkdir()

    cpacs = CPACS(CPACS_IN_PATH)

    export_brep(cpacs, TEST_OUT_PATH)

    brep_files = list(TEST_OUT_PATH.glob("*.brep"))
    brep_file_names = [brep_file.name for brep_file in brep_files]

    assert len(brep_files) == 3  # simpletest_cpacs.xml containt only 3 parts
    assert "Wing.brep" in brep_file_names
    assert "Wing_mirrored.brep" in brep_file_names
    assert "SimpleFuselage.brep" in brep_file_names

    # Erase brep file generated by the test
    for brep_file in brep_files:
        brep_file.unlink()

    with pytest.raises(FileNotFoundError):
        with patch(f"ceasiompy.{CPACS2GMSH}.func.exportbrep.export_shapes", return_value=True):
            export_brep(cpacs, TEST_OUT_PATH)


# Main
if __name__ == "__main__":
    print("Test CPACS2GMSH")
    print("To run test use the following command:")
    print(">> pytest -v")
