site_name: scope user manual
copyright: 2016 <a href=mailto:david@larosterna.com>David Eller</a>
pages:
  - Home: index.md
  - File Formats: formats.md
  - Data Display: display.md
  - Mesh Editing: edit.md
  - Deformation Mapping: mapping.md
  - Load Analysis: loads.md
theme: 'readthedocs'
extra_css: [larosterna.css, offlinefonts.css]
use_directory_urls: false
markdown_extensions:
  - smarty
  - attr_list
  - def_list
  - footnotes
  - admonition
