"""
CEASIOMpy: Conceptual Aircraft Design Software

Developed by CFS ENGINEERING, 1015 Lausanne, Switzerland

Test functions for 'lib/ModuleTemplate/moduletemplate.py'

Python version: >=3.7

| Author : Tony Govoni
| Creation: 2022-03-22

"""

# ==============================================================================
#   IMPORTS
# ==============================================================================

from pathlib import Path
from cpacspy.cpacspy import CPACS

from ceasiompy.CPACS2GMSH.func.exportbrep import export_brep

MODULE_DIR = Path(__file__).parent
CPACS_IN_PATH = Path(MODULE_DIR, "ToolInput", "simpletest_cpacs.xml")
TEST_OUT_PATH = Path(MODULE_DIR, "ToolOutput")


# ==============================================================================
#   CLASSES
# ==============================================================================


# ==============================================================================
#   FUNCTIONS
# ==============================================================================


def test_export_brep():
    """Test function for 'export_brep'"""

    cpacs = CPACS(str(CPACS_IN_PATH))

    export_brep(cpacs, TEST_OUT_PATH)

    brep_files = list(TEST_OUT_PATH.glob("*.brep"))
    brep_file_names = [brep_file.name for brep_file in brep_files]

    assert len(brep_files) == 3  # simpletest_cpacs.xml containt only 3 parts
    assert "Wing.brep" in brep_file_names
    assert "Wing_mirrored.brep" in brep_file_names
    assert "SimpleFuselage.brep" in brep_file_names

    # Erase brep file generated by the test
    for brep_file in brep_files:
        brep_file.unlink()


# ==============================================================================
#    MAIN
# ==============================================================================

if __name__ == "__main__":

    print("Test CPACS2GMSH")
    print("To run test use the following command:")
    print(">> pytest -v")
