
name: Installation test on CentOS with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
     
    - name: Run integration tests
      shell: bash -l {0}
      run: |
        source ~/.bashrc
        cd /CEASIOMpy/tests/docker/Centos/
        docker build -f Dockerfile .

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-logs
        path: tests/workflow_tests/**/ceasiompy.log