
name: Installation and tests on CentOS with Docker

on:
  schedule:
    - cron: '0 2 * * 1'  # every Monday at 2:00am

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.11.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.11
     
    - name: Run Dockerfile installation and tests
      run: |
        docker build -t ceasiompy-centos:latest -f tests/docker/Centos/Dockerfile .
        docker run --rm -v ${{ github.workspace }}:/CEASIOMpyDir/CEASIOMpy ceasiompy-centos
