name: Unittest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 2 * * 1'  # every Monday at 2:00am

env:
  CACHE_NUMBER: 1  # increase to reset cache manually
  CONDA_RETRIES: 3
  CONDA_TIMEOUT: 20

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Updated to v4

    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Setup MiniConda3
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        activate-environment: ceasiompy # This keeps the env active for all 'bash -l' steps
        environment-file: environment.yml
        use-mamba: true # Mamba is much faster and more reliable than Conda for solving envs

    - name: Install libGLU
      run: sudo apt-get install -y libglu1-mesa-dev

    - name: Install ceasiompy and Pentagrow
      shell: bash -l {0}
      run: |
        pip install -e .
        installation/ubuntu/pentagrow.sh

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        # No source ~/.bashrc needed because of 'shell: bash -l {0}' and 'activate-environment'
        pytest -v src/ceasiompy \
          --ignore=src/ceasiompy/vsp2cpacs/tests/test_vsp2cpacs.py \
          --cov=ceasiompy --cov-report xml:coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
